#############################################################################
#!
#! This is a tmake template for creating a makefile that invokes make in
#! sub directories - for Win32.
#!
#${
    StdInit();
#$}
#!
# Makefile for building targets in sub directories.
# Generated by tmake at #$ Now();
#     Project: #$ Expand("PROJECT");
#    Template: #$ Expand("TEMPLATE");
#############################################################################

REMOVE  =	-del
SUBDIRS =	#$ ExpandList("SUBDIRS");

all: $(SUBDIRS)

clean:
	$(MAKE) all ACTION=clean

dist:
	$(MAKE) all ACTION=dist
	$(REMOVE) Makefile #$ Expand('TMAKE_DIST_FILES');

#${
  foreach ( split(/\s+/,$project{"SUBDIRS"}) ) {
    my $backpath = $_; $backpath =~ s/\w*/\./g;
    $text = $text . $_ . ": FORCE\n\t" .
    "cd $_\n\t\$(MAKE\) \$(ACTION)\n\t\@cd $backpath\n\n"; }
#$}
FORCE:
